### ISSUE TITLE
PG error for long queries

### ISSUE THREAD

**Issue by sergey-alekseev** [panorama-ed/order_as_specified#34]
Try running [a long query](https://gist.github.com/sergey-alekseev/d637c5a24db3e49b4dd6966559dc36f0). You'll get an error `target lists can have at most 1664 entries`. The full error in Rails is `PG::ProgramLimitExceeded: ERROR: target lists can have at most 1664 entries`.

**Comment by JacobEvelyn** [comment]
Good find, @sergey-alekseev! Since this is a Postgres limitation it looks like there's not anything we can do to fix it unfortunately. Do you think the right behavior in this case would be to raise an `ArgumentError` if the input list is too large?

**Comment by sergey-alekseev** [comment]
@JacobEvelyn yes, raising an `ArgumentError` with a clarification would be great. I wanted to make it clear for others, so they can google this problem if it occurs and find this issue. However your approach would be even better. I'm not going to implement this approach to be clear.  

Thanks for the gem!

**Comment by JacobEvelyn** [comment]
Thanks for the thought here, @sergey-alekseev. After thinking about this a bit more I'm not sure we want to raise an `ArgumentError` if the input array is too big because the user could be using a different database (or a future version of Postgres) with a higher limit than what we hardcode.

We can't really catch the `PG::ProgramLimitExceeded` error because of the way `ActiveRecord::Relation`s chain... the actual query execution will occur outside of this gem's code.

I think the sanest path forward is probably to just put a warning in the README. I'll work on that.

**Comment by sergey-alekseev** [comment]
@JacobEvelyn yeah, sounds good. As far as others can google this issue it shouldn't cause much trouble. It took me some time to find the exact problem, so I described the problem here. Also it may be a rare issue in general.
