### ISSUE TITLE
Queries with `DISTINCT` require all ORDER BY fields to be in the SELECT.

### ISSUE THREAD

**Issue by jeffnappi** [panorama-ed/order_as_specified#45]
I'm running into an issue where I need to also include the `CASE` statement in the select columns of a query. Unfortunately there doesn't seem to be a simple way to do this with `order_as_specified`.

The error message is:
`PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list`

In my case I am currently working around this without `order_as_specified` by just passing the `CASE` statement via `select()` as well as `order()`

**Comment by JacobEvelyn** [comment]
Thanks for opening this issue, @jeffnappi, and sorry for the slow response. I think we can probably figure out a solution here but I want to make sure I fully understand what you're looking for. Since we already support a `distinct_on` for `DISTINCT ON` queries I want to make sure that's not what you want.

Could you give me a sample query that you're producing with the manual `select()` and `order()` calls, or a little bit more info about what your query is?

**Comment by JacobEvelyn** [comment]
@jeffnappi it's been a while—can you shed any more light on what you're running into here, or should we close this out?

**Comment by jeffnappi** [comment]
Hi @JacobEvelyn, we can close it out. I came up with a workaround, but at this point, I don't recall the specifics :flushed: My apologies for not followup up previously.
