### ISSUE TITLE
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list

### ISSUE THREAD

**Issue by culov** [panorama-ed/order_as_specified#64]
Hi,

I'm trying to use this great looking gem to order an ActiveRecord relation, so that items appearing in a second array, are sorted at the beginning of the ActiveRecord relation.

Here's how I'm doing it:

```
@sort_first_ids = @sort_first.pluck(:id)
@base_query.order_as_specified( id: @sort_first_ids)
```

Now, the problem is that it appears to generate an invalid query and I'm not sure why. It appears that PostgreSQL has a problem with the CASE keyword in the query. Below is the error I see when I try running the query above. Does anyone have any thoughts on how to fix this query?

```
ActiveRecord::StatementInvalid (PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list)
LINE 1: ...$63, $64, $65, $66, $67, $68, $69, $70) ORDER BY (CASE WHEN
```

**Comment by JacobEvelyn** [comment]
Hi @culov! Based on the error message:

```
for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

I don't think your issue has anything to do with the `CASE` keyword. It's hard for me to say exactly without seeing the full query you're trying to execute (you can get the full query with `@base_query.order_as_specified(id: @sort_first_ids).to_sql`), but it appears your `@base_query` is adding a `DISTINCT` clause.

Postgres has some limitations on how `DISTINCT` and `ORDER BY` can interact (one explanation is [here](https://stackoverflow.com/a/12693353)), but it's possible what you really want is to use the `OrderAsSpecified` [`distinct_on`](https://github.com/panorama-ed/order_as_specified#distinct_on) feature instead of the `DISTINCT` you've added in `@base_query`.

Hope that helps!

**Comment by culov** [comment]
Thank you @JacobEvelyn, removing a previously added `distinct` from the Active Record relation fixed it!

The execution of the query however, did slow down considerably and I'm wondering if that's expected. In my query `@base_query.order_as_specified( id: @sort_first_ids)`, `@base_query` is about 40,000 records, and @sort_first_ids is about 600 ids.

Without `order_as_specified`, the query executes on average in 500 ms. With `order_as_specified`, it's averaging about 21 seconds. Is this expected with a large number of records or is there perhaps a better approach I can take?

**Comment by JacobEvelyn** [comment]
@culov I'm actually not sure. My instinct is that 600 elements is a lot to put into `order_as_specified` because that will result in a very large `CASE` statement being generated in your query. If the order of `@sort_first_ids` doesn't matter and you just want all of those _before_ the other records, you could try writing a custom ordering instead like:

```ruby
@base_query.order("CASE WHEN client_id IN (#{@sort_first_ids.join(',')}) THEN 0 ELSE 1 END")
```

which I anticipate being much faster but can't say for sure.

**Comment by culov** [comment]
@JacobEvelyn Thank you! Yes, that approach cut the execution time of the query down by 75%. Thank you so much for your help.

**Comment by JacobEvelyn** [comment]
Glad to hear it, @culov !
